-- MySQL Script generated by MySQL Workbench
-- Sun May 21 11:49:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema appweb_AutOsiris
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `appweb_AutOsiris` ;

-- -----------------------------------------------------
-- Schema appweb_AutOsiris
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `appweb_AutOsiris` DEFAULT CHARACTER SET utf8 ;
USE `appweb_AutOsiris` ;


-- -----------------------------------------------------
-- Table `appweb_AutOsiris`.`ROL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appweb_AutOsiris`.`ROL` ;

CREATE TABLE IF NOT EXISTS `appweb_AutOsiris`.`ROL` (
  `idRol` INT NOT NULL,
  `nombreRol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appweb_AutOsiris`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appweb_AutOsiris`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `appweb_AutOsiris`.`CLIENTE` (
  `idCliente` INT NOT NULL,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `direccionCliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appweb_AutOsiris`.`DISTRIBUIDOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appweb_AutOsiris`.`DISTRIBUIDOR` ;

CREATE TABLE IF NOT EXISTS `appweb_AutOsiris`.`DISTRIBUIDOR` (
  `idDistribuidor` INT NOT NULL,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idDistribuidor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appweb_AutOsiris`.`VENDEDOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appweb_AutOsiris`.`VENDEDOR` ;

CREATE TABLE IF NOT EXISTS `appweb_AutOsiris`.`VENDEDOR` (
  `idAdministrador` INT NOT NULL,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idAdministrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appweb_AutOsiris`.`USUARIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appweb_AutOsiris`.`USUARIOS` ;

CREATE TABLE IF NOT EXISTS `appweb_AutOsiris`.`USUARIOS` (
  `idUsuario` INT NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `acceso` VARCHAR(45) NOT NULL,
  `tipoDocumento` VARCHAR(45) NOT NULL,
  `numDocumento` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `numCelular` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `ADMINISTRADOR_idAdministrador` INT NOT NULL,
  `CLIENTE_idCliente` INT NOT NULL,
  `DISTRIBUIDOR_idDistribuidor` INT NOT NULL,
  `ROL_idRol` INT NOT NULL,
  `CLIENTE_idCliente1` INT NOT NULL,
  `DISTRIBUIDOR_idDistribuidor1` INT NOT NULL,
  `VENDEDOR_idAdministrador` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `ADMINISTRADOR_idAdministrador`, `CLIENTE_idCliente`, `DISTRIBUIDOR_idDistribuidor`),
  INDEX `fk_USUARIOS_ROL1_idx` (`ROL_idRol` ASC),
  INDEX `fk_USUARIOS_CLIENTE1_idx` (`CLIENTE_idCliente1` ASC),
  INDEX `fk_USUARIOS_DISTRIBUIDOR1_idx` (`DISTRIBUIDOR_idDistribuidor1` ASC),
  INDEX `fk_USUARIOS_VENDEDOR1_idx` (`VENDEDOR_idAdministrador` ASC),
  CONSTRAINT `fk_USUARIOS_ROL1`
    FOREIGN KEY (`ROL_idRol`)
    REFERENCES `appweb_AutOsiris`.`ROL` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOS_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCliente1`)
    REFERENCES `appweb_AutOsiris`.`CLIENTE` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOS_DISTRIBUIDOR1`
    FOREIGN KEY (`DISTRIBUIDOR_idDistribuidor1`)
    REFERENCES `appweb_AutOsiris`.`DISTRIBUIDOR` (`idDistribuidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOS_VENDEDOR1`
    FOREIGN KEY (`VENDEDOR_idAdministrador`)
    REFERENCES `appweb_AutOsiris`.`VENDEDOR` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appweb_AutOsiris`.`CREDENCIALES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appweb_AutOsiris`.`CREDENCIALES` ;

CREATE TABLE IF NOT EXISTS `appweb_AutOsiris`.`CREDENCIALES` (
  `idCredencial` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `nombreUsuario` VARCHAR(20) NOT NULL,
  `acceso` VARCHAR(45) NOT NULL,
  `USUARIOS_idUsuario` INT NOT NULL,
  `USUARIOS_ADMINISTRADOR_idAdministrador` INT NOT NULL,
  `USUARIOS_CLIENTE_idCliente` INT NOT NULL,
  `USUARIOS_DISTRIBUIDOR_idDistribuidor` INT NOT NULL,
  PRIMARY KEY (`idCredencial`, `idUsuario`, `nombreUsuario`, `contraseña`),
  UNIQUE INDEX `idCredencial_UNIQUE` (`idCredencial` ASC),
  INDEX `fk_CREDENCIALES_USUARIOS1_idx` (`USUARIOS_idUsuario` ASC, `USUARIOS_ADMINISTRADOR_idAdministrador` ASC, `USUARIOS_CLIENTE_idCliente` ASC, `USUARIOS_DISTRIBUIDOR_idDistribuidor` ASC),
  CONSTRAINT `fk_CREDENCIALES_USUARIOS1`
    FOREIGN KEY (`USUARIOS_idUsuario` , `USUARIOS_ADMINISTRADOR_idAdministrador` , `USUARIOS_CLIENTE_idCliente` , `USUARIOS_DISTRIBUIDOR_idDistribuidor`)
    REFERENCES `appweb_AutOsiris`.`USUARIOS` (`idUsuario` , `ADMINISTRADOR_idAdministrador` , `CLIENTE_idCliente` , `DISTRIBUIDOR_idDistribuidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appweb_AutOsiris`.`MENSAJES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appweb_AutOsiris`.`MENSAJES` ;

CREATE TABLE IF NOT EXISTS `appweb_AutOsiris`.`MENSAJES` (
  `idMensaje` INT NOT NULL,
  `idAdministrador` INT NOT NULL,
  `idDistribuidor` INT NOT NULL,
  `destinatario` VARCHAR(45) NOT NULL,
  `asunto` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `fecha_envio` DATE NULL,
  `VENDEDOR_idAdministrador` INT NOT NULL,
  `DISTRIBUIDOR_idDistribuidor` INT NOT NULL,
  PRIMARY KEY (`idMensaje`, `idAdministrador`, `idDistribuidor`),
  INDEX `fk_MENSAJES_VENDEDOR1_idx` (`VENDEDOR_idAdministrador` ASC),
  INDEX `fk_MENSAJES_DISTRIBUIDOR1_idx` (`DISTRIBUIDOR_idDistribuidor` ASC),
  CONSTRAINT `fk_MENSAJES_VENDEDOR1`
    FOREIGN KEY (`VENDEDOR_idAdministrador`)
    REFERENCES `appweb_AutOsiris`.`VENDEDOR` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MENSAJES_DISTRIBUIDOR1`
    FOREIGN KEY (`DISTRIBUIDOR_idDistribuidor`)
    REFERENCES `appweb_AutOsiris`.`DISTRIBUIDOR` (`idDistribuidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appweb_AutOsiris`.`LISTA_PRODUCTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appweb_AutOsiris`.`LISTA_PRODUCTOS` ;

CREATE TABLE IF NOT EXISTS `appweb_AutOsiris`.`LISTA_PRODUCTOS` (
  `idPedido` INT NOT NULL,
  `idProducto` INT NULL,
  `cantidadProducto` INT NOT NULL,
  `PEDIDO_idPedido` INT NOT NULL,
  PRIMARY KEY (`idPedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appweb_AutOsiris`.`PEDIDO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appweb_AutOsiris`.`PEDIDO` ;

CREATE TABLE IF NOT EXISTS `appweb_AutOsiris`.`PEDIDO` (
  `idPedido` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `idCliente` INT NOT NULL,
  `nombreProducto` VARCHAR(45) NOT NULL,
  `cantidadProducto` INT NOT NULL,
  `totalPedido` FLOAT NOT NULL,
  `IVA` FLOAT NOT NULL,
  `LISTA_PRODUCTOS_idPedido` INT NOT NULL,
  `VENDEDOR_idAdministrador` INT NOT NULL,
  `CLIENTE_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_PEDIDO_LISTA_PRODUCTOS1_idx` (`LISTA_PRODUCTOS_idPedido` ASC),
  INDEX `fk_PEDIDO_VENDEDOR1_idx` (`VENDEDOR_idAdministrador` ASC),
  INDEX `fk_PEDIDO_CLIENTE1_idx` (`CLIENTE_idCliente` ASC),
  CONSTRAINT `fk_PEDIDO_LISTA_PRODUCTOS1`
    FOREIGN KEY (`LISTA_PRODUCTOS_idPedido`)
    REFERENCES `appweb_AutOsiris`.`LISTA_PRODUCTOS` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_VENDEDOR1`
    FOREIGN KEY (`VENDEDOR_idAdministrador`)
    REFERENCES `appweb_AutOsiris`.`VENDEDOR` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCliente`)
    REFERENCES `appweb_AutOsiris`.`CLIENTE` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appweb_AutOsiris`.`PRODUCTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appweb_AutOsiris`.`PRODUCTOS` ;

CREATE TABLE IF NOT EXISTS `appweb_AutOsiris`.`PRODUCTOS` (
  `idProducto` INT NOT NULL,
  `idCategoria` VARCHAR(45) NULL,
  `nombreProducto` VARCHAR(45) NOT NULL,
  `tipoProducto` VARCHAR(45) NULL,
  `codProducto` VARCHAR(45) NOT NULL,
  `fechaCompra` DATE NULL,
  `LISTA_PRODUCTOS_idPedido` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_PRODUCTOS_LISTA_PRODUCTOS1_idx` (`LISTA_PRODUCTOS_idPedido` ASC),
  CONSTRAINT `fk_PRODUCTOS_LISTA_PRODUCTOS1`
    FOREIGN KEY (`LISTA_PRODUCTOS_idPedido`)
    REFERENCES `appweb_AutOsiris`.`LISTA_PRODUCTOS` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `appweb_AutOsiris`.`CATEGORIAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appweb_AutOsiris`.`CATEGORIAS` ;

CREATE TABLE IF NOT EXISTS `appweb_AutOsiris`.`CATEGORIAS` (
  `idCategoria` INT NOT NULL,
  `nombreProducto` VARCHAR(45) NULL,
  `idProducto` VARCHAR(45) NULL,
  `tipoProducto` VARCHAR(45) NULL,
  `PRODUCTOS_idProducto` INT NOT NULL,
  PRIMARY KEY (`idCategoria`),
  INDEX `fk_CATEGORIAS_PRODUCTOS1_idx` (`PRODUCTOS_idProducto` ASC),
  CONSTRAINT `fk_CATEGORIAS_PRODUCTOS1`
    FOREIGN KEY (`PRODUCTOS_idProducto`)
    REFERENCES `appweb_AutOsiris`.`PRODUCTOS` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
