-- MySQL Script generated by MySQL Workbench
-- Sun May  7 10:16:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineeringsss


-- -----------------------------------------------------
-- Schema appweb_bd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `appweb_bd` ;

-- -----------------------------------------------------
-- Schema appweb_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `appweb_bd` DEFAULT CHARACTER SET utf8 ;
USE `appweb_bd` ;

-- -----------------------------------------------------
-- Table `appweb_bd`.`ROLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appweb_bd`.`ROLES` ;

CREATE TABLE IF NOT EXISTS `appweb_bd`.`ROLES` (
  `idRol` INT NOT NULL,
  `nombre_rol` VARCHAR(50) NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appweb_bd`.`USUARIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appweb_bd`.`USUARIOS` ;

CREATE TABLE IF NOT EXISTS `appweb_bd`.`USUARIOS` (
  `id_rol` INT NOT NULL,
  `id_usuario` VARCHAR(50) NOT NULL,
  `nombres_usuario` VARCHAR(100) NOT NULL,
  `apellidos_usuario` VARCHAR(100) NOT NULL,
  `correo_usuario` VARCHAR(100) NOT NULL,
  `contraseña_usuario` VARCHAR(15) NOT NULL,
  `ROLES_idRol` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_USUARIOS_ROLES1_idx` (`ROLES_idRol` ASC),
  CONSTRAINT `fk_USUARIOS_ROLES1`
    FOREIGN KEY (`ROLES_idRol`)
    REFERENCES `appweb_bd`.`ROLES` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appweb_bd`.`CLIENTES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appweb_bd`.`CLIENTES` ;

CREATE TABLE IF NOT EXISTS `appweb_bd`.`CLIENTES` (
  `id_cliente` VARCHAR(50) NOT NULL,
  `direccion_cliente` VARCHAR(45) NULL,
  `USUARIOS_id_usuario` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_CLIENTES_USUARIOS1_idx` (`USUARIOS_id_usuario` ASC),
  CONSTRAINT `fk_CLIENTES_USUARIOS1`
    FOREIGN KEY (`USUARIOS_id_usuario`)
    REFERENCES `appweb_bd`.`USUARIOS` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appweb_bd`.`PEDIDO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appweb_bd`.`PEDIDO` ;

CREATE TABLE IF NOT EXISTS `appweb_bd`.`PEDIDO` (
  `id_cliente` VARCHAR(50) NOT NULL,
  `id_pedido` VARCHAR(10) NOT NULL,
  `fecha_pedido` DATE NULL,
  `CLIENTES_id_cliente` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_PEDIDO_CLIENTES1_idx` (`CLIENTES_id_cliente` ASC),
  CONSTRAINT `fk_PEDIDO_CLIENTES1`
    FOREIGN KEY (`CLIENTES_id_cliente`)
    REFERENCES `appweb_bd`.`CLIENTES` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `appweb_bd`.`CATEGORIAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appweb_bd`.`CATEGORIAS` ;

CREATE TABLE IF NOT EXISTS `appweb_bd`.`CATEGORIAS` (
  `id_categoria` INT NOT NULL,
  `nombre_categoria` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appweb_bd`.`PRODUCTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appweb_bd`.`PRODUCTOS` ;


CREATE TABLE IF NOT EXISTS `appweb_bd`.`PRODUCTOS` (
  `id_categoria` INT NOT NULL,
  `id_producto` VARCHAR(50) NOT NULL,
  `nombre_producto` VARCHAR(150) NOT NULL,
  `CATEGORIAS_id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_PRODUCTOS_CATEGORIAS1_idx` (`CATEGORIAS_id_categoria` ASC),
  CONSTRAINT `fk_PRODUCTOS_CATEGORIAS1`
    FOREIGN KEY (`CATEGORIAS_id_categoria`)
    REFERENCES `appweb_bd`.`CATEGORIAS` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `appweb_bd`.`LISTA_PRODUCTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appweb_bd`.`LISTA_PRODUCTOS` ;

CREATE TABLE IF NOT EXISTS `appweb_bd`.`LISTA_PRODUCTOS` (
  `id_pedido` VARCHAR(10) NOT NULL,
  `id_producto` VARCHAR(50) NOT NULL,
  `cantidad_producto` INT NULL,
  `PEDIDO_id_pedido` VARCHAR(10) NOT NULL,
  `PRODUCTOS_id_producto` VARCHAR(50) NOT NULL,
  INDEX `fk_LISTA_PRODUCTOS_PEDIDO1_idx` (`PEDIDO_id_pedido` ASC),
  INDEX `fk_LISTA_PRODUCTOS_PRODUCTOS1_idx` (`PRODUCTOS_id_producto` ASC),
  CONSTRAINT `fk_LISTA_PRODUCTOS_PEDIDO1`
    FOREIGN KEY (`PEDIDO_id_pedido`)
    REFERENCES `appweb_bd`.`PEDIDO` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LISTA_PRODUCTOS_PRODUCTOS1`
    FOREIGN KEY (`PRODUCTOS_id_producto`)
    REFERENCES `appweb_bd`.`PRODUCTOS` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

