-- MySQL Script generated by MySQL Workbench
-- Mon Jun 19 21:15:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema autosiris_bbdd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `autosiris_bbdd` ;

-- -----------------------------------------------------
-- Schema autosiris_bbdd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autosiris_bbdd` DEFAULT CHARACTER SET utf8 ;
USE `autosiris_bbdd` ;

-- ELiminar la base de datos
-- DROP DATABASE autosiris_bbdd;


-- -----------------------------------------------------
-- Table `autosiris_bbdd`.`ROLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autosiris_bbdd`.`ROLES` ;

CREATE TABLE IF NOT EXISTS `autosiris_bbdd`.`ROLES` (
  `idRol` INT NULL,
  `nombreRol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autosiris_bbdd`.`USUARIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autosiris_bbdd`.`USUARIOS` ;

CREATE TABLE IF NOT EXISTS `autosiris_bbdd`.`USUARIOS` (
  `idUsuario` INT NULL,
  `nombrePersona` VARCHAR(45) NOT NULL,
  `apellidoPersona` VARCHAR(45) NOT NULL,
  `correoElectronico` VARCHAR(100) NOT NULL,
  `nombreUsuario` VARCHAR(20) NOT NULL,
  `contraseña` VARCHAR(50) NOT NULL,
  `ROLES_idRol` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_USUARIOS_ROLES_idx` (`ROLES_idRol` ASC),
  CONSTRAINT `fk_USUARIOS_ROLES`
    FOREIGN KEY (`ROLES_idRol`)
    REFERENCES `autosiris_bbdd`.`ROLES` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autosiris_bbdd`.`VENDEDOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autosiris_bbdd`.`VENDEDOR` ;

CREATE TABLE IF NOT EXISTS `autosiris_bbdd`.`VENDEDOR` (
  `USUARIOS_idUsuario` INT NOT NULL,
  INDEX `fk_VENDEDOR_USUARIOS1_idx` (`USUARIOS_idUsuario` ASC),
  CONSTRAINT `fk_VENDEDOR_USUARIOS1`
    FOREIGN KEY (`USUARIOS_idUsuario`)
    REFERENCES `autosiris_bbdd`.`USUARIOS` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autosiris_bbdd`.`CATEGORIAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autosiris_bbdd`.`CATEGORIAS` ;

CREATE TABLE IF NOT EXISTS `autosiris_bbdd`.`CATEGORIAS` (
  `idCategoria` INT NULL,
  `nombreCategoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autosiris_bbdd`.`PRODUCTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autosiris_bbdd`.`PRODUCTOS` ;

CREATE TABLE IF NOT EXISTS `autosiris_bbdd`.`PRODUCTOS` (
  `idProducto` INT NULL,
  `codigoProducto` VARCHAR(20) NOT NULL,
  `precioProducto` FLOAT NOT NULL,
  `nombreProducto` VARCHAR(45) NOT NULL,
  `descripcionProducto` VARCHAR(100) NOT NULL,
  `imagenProducto` BLOB NOT NULL,
  `entradaProducto` INT NOT NULL,
  `fechaEntradaProducto` DATE NOT NULL,
  `salidaProducto` INT NOT NULL,
  `fechaSalidaProducto` DATE NOT NULL,
  `stockProducto` INT NOT NULL,
  `CATEGORIAS_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idProducto`, `codigoProducto`, `precioProducto`),
  INDEX `fk_PRODUCTOS_CATEGORIAS1_idx` (`CATEGORIAS_idCategoria` ASC),
  CONSTRAINT `fk_PRODUCTOS_CATEGORIAS1`
    FOREIGN KEY (`CATEGORIAS_idCategoria`)
    REFERENCES `autosiris_bbdd`.`CATEGORIAS` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autosiris_bbdd`.`LISTA_PRODUCTOS_COMPRADOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autosiris_bbdd`.`LISTA_PRODUCTOS_COMPRADOS` ;

CREATE TABLE IF NOT EXISTS `autosiris_bbdd`.`LISTA_PRODUCTOS_COMPRADOS` (
  `cantidadProducto` INT NULL,
  `PRODUCTOS_idProducto` INT NOT NULL,
  `PRODUCTOS_codigoProducto` VARCHAR(20) NOT NULL,
  `PRODUCTOS_precioProducto` FLOAT NOT NULL,
  PRIMARY KEY (`cantidadProducto`, `PRODUCTOS_idProducto`),
  INDEX `fk_LISTA_PRODUCTOS_COMPRADOS_PRODUCTOS1_idx` (`PRODUCTOS_idProducto` ASC, `PRODUCTOS_codigoProducto` ASC, `PRODUCTOS_precioProducto` ASC),
  CONSTRAINT `fk_LISTA_PRODUCTOS_COMPRADOS_PRODUCTOS1`
    FOREIGN KEY (`PRODUCTOS_idProducto` , `PRODUCTOS_codigoProducto` , `PRODUCTOS_precioProducto`)
    REFERENCES `autosiris_bbdd`.`PRODUCTOS` (`idProducto` , `codigoProducto` , `precioProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autosiris_bbdd`.`VENTAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autosiris_bbdd`.`VENTAS` ;

CREATE TABLE IF NOT EXISTS `autosiris_bbdd`.`VENTAS` (
  `idVenta` INT NULL,
  `fechaCompra` DATE NOT NULL,
  `precioTotal` FLOAT NOT NULL,
  `totalProductos` FLOAT NOT NULL,
  `LISTA_PRODUCTOS_COMPRADOS_cantidadProducto` INT NOT NULL,
  PRIMARY KEY (`idVenta`, `fechaCompra`, `precioTotal`, `totalProductos`),
  INDEX `fk_VENTAS_LISTA_PRODUCTOS_COMPRADOS1_idx` (`LISTA_PRODUCTOS_COMPRADOS_cantidadProducto` ASC),
  CONSTRAINT `fk_VENTAS_LISTA_PRODUCTOS_COMPRADOS1`
    FOREIGN KEY (`LISTA_PRODUCTOS_COMPRADOS_cantidadProducto`)
    REFERENCES `autosiris_bbdd`.`LISTA_PRODUCTOS_COMPRADOS` (`cantidadProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autosiris_bbdd`.`FACTURAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autosiris_bbdd`.`FACTURAS` ;

CREATE TABLE IF NOT EXISTS `autosiris_bbdd`.`FACTURAS` (
  `idFactura` INT NULL,
  `nombreFactura` VARCHAR(45) NOT NULL,
  `VENTAS_idVenta` INT NOT NULL,
  `VENTAS_fechaCompra` DATE NOT NULL,
  `VENTAS_precioTotal` FLOAT NOT NULL,
  `VENTAS_totalProductos` FLOAT NOT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `fk_FACTURAS_VENTAS1_idx` (`VENTAS_idVenta` ASC, `VENTAS_fechaCompra` ASC, `VENTAS_precioTotal` ASC, `VENTAS_totalProductos` ASC),
  CONSTRAINT `fk_FACTURAS_VENTAS1`
    FOREIGN KEY (`VENTAS_idVenta` , `VENTAS_fechaCompra` , `VENTAS_precioTotal` , `VENTAS_totalProductos`)
    REFERENCES `autosiris_bbdd`.`VENTAS` (`idVenta` , `fechaCompra` , `precioTotal` , `totalProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;